// This file was automatically generated by the Dapper.SimpleCRUD T4 Template
// Do not make changes directly to this file - edit the template instead
// 
// The following connection settings were used to generate this file
// 
//     Connection String Name: `CrestDB`
//     Provider:               `System.Data.SqlClient`
//     Connection String:      `Data Source=(LocalDB)\v11.0;AttachDbFilename=F:\Projects\Websites\Crest\Crest.Web\Crest.Web\App_Data\CrestDB.mdf;Integrated Security=True`
//     Include Views:          `True`

using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Crest.Web.Models
{
    /// <summary>
    /// A class which represents the Applications table.
    /// </summary>
	[Table("Applications")]
	public partial class Application
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual string Name { get; set; }
	}

    /// <summary>
    /// A class which represents the Errors table.
    /// </summary>
	[Table("Errors")]
	public partial class Error
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual int ApplicationId { get; set; }
		public virtual string Host { get; set; }
		public virtual string Type { get; set; }
		public virtual string Source { get; set; }
		public virtual string Message { get; set; }
		public virtual string User { get; set; }
		public virtual int StatusCode { get; set; }
		public virtual DateTime TimeUtc { get; set; }
		public virtual string JsonInfo { get; set; }
	}

}
